var fbsTeams = new Map ([
    ["California Golden Bears", 25],
    ["Stanford Cardinal", 24],
    ["Clemson Tigers", 228],
    ["Georgia Tech Yellow Jackets", 59],
    ["Florida State Seminoles", 52],
    ["Louisville Cardinals", 97],
    ["North Carolina Tar Heels", 153],
    ["NC State Wolfpack", 152],
    ["SMU Mustangs", 2567],
    ["Virginia Cavaliers", 258],
    ["Miami Hurricanes", 2390],
    ["North Texas Mean Green", 249],
    ["Arizona Wildcats", 12],
    ["Syracuse Orange", 183],
    ["Army Black Knights", 349],
    ["Tulane Green Wave", 2655],
    ["Virginia Tech Hokies", 259],
    ["UAB Blazers", 5],
    ["Florida Atlantic Owls", 2226],
    ["UTSA Roadrunners", 2636],
    ["Memphis Tigers", 235],
    ["BYU Cougars", 252],
    ["Iowa State Cyclones", 66],
    ["Navy Midshipmen", 2426],
    ["Arizona State Sun Devils", 9],
    ["Houston Cougars", 248],
    ["Temple Owls", 218],
    ["Kansas State Wildcats", 2306],
    ["Texas Tech Red Raiders", 2641],
    ["Rice Owls", 242],
    ["Pittsburgh Panthers", 221],
    ["TCU Horned Frogs", 2628],
    ["Baylor Bears", 239],
    ["Utah Utes", 254],
    ["Iowa Hawkeyes", 2294],
    ["Indiana Hoosiers", 84],
    ["Michigan Wolverines", 130],
    ["Minnesota Golden Gophers", 135],
    ["UCLA Bruins", 26],
    ["Northwestern Wildcats", 77],
    ["Wake Forest Demon Deacons", 154],
    ["UCF Knights", 2116],
    ["Wisconsin Badgers", 275],
    ["Florida International Panthers", 2229],
    ["Maryland Terrapins", 120],
    ["Purdue Boilermakers", 2509],
    ["Middle Tennessee Blue Raiders", 2393],
    ["Kennesaw State Owls", 338],
    ["Tulsa Golden Hurricane", 202],
    ["Rutgers Scarlet Knights", 164],
    ["East Carolina Pirates", 151],
    ["Jacksonville State Gamecocks", 55],
    ["UConn Huskies", 41],
    ["Colorado Buffaloes", 38],
    ["Western Kentucky Hilltoppers", 98],
    ["UTEP Miners", 2638],
    ["USC Trojans", 30],
    ["Hawai'i Rainbow Warriors", 62],
    ["Ohio Bobcats", 195],
    ["Kent State Golden Flashes", 2309],
    ["Sam Houston Bearkats", 2534],
    ["Central Michigan Chippewas", 2117],
    ["Cincinnati Bearcats", 2132],
    ["Toledo Rockets", 2649],
    ["Akron Zips", 2006],
    ["Florida Gators", 57],
    ["West Virginia Mountaineers", 277],
    ["Tennessee Volunteers", 2633],
    ["Oregon State Beavers", 204],
    ["UNLV Rebels", 2439],
    ["Washington Huskies", 264],
    ["Coastal Carolina Chanticleers", 324],
    ["Oregon Ducks", 2483],
    ["James Madison Dukes", 256],
    ["Arkansas Razorbacks", 8],
    ["Northern Illinois Huskies", 2459],
    ["Oklahoma Sooners", 201],
    ["Utah State Aggies", 328],
    ["Louisiana Ragin' Cajuns", 309],
    ["Penn State Nittany Lions", 213],
    ["LSU Tigers", 99],
    ["Georgia Bulldogs", 61],
    ["Ball State Cardinals", 2050],
    ["Boston College Eagles", 103],
    ["Missouri Tigers", 142],
    ["Texas A&M Aggies", 245],
    ["Liberty Flames", 2335],
    ["San Diego State Aztecs", 21],
    ["Colorado State Rams", 36],
    ["App State Mountaineers", 2026],
    ["Auburn Tigers", 2],
    ["Boise State Broncos", 68],
    ["Ohio State Buckeyes", 194],
    ["Notre Dame Fighting Irish", 87],
    ["South Alabama Jaguars", 6],
    ["Arkansas State Red Wolves", 2032],
    ["Kansas Jayhawks", 2305],
    ["Bowling Green Falcons", 189],
    ["Georgia Southern Eagles", 290],
    ["Fresno State Bulldogs", 278],
    ["UL Monroe Warhawks", 2433],
    ["Miami (OH) RedHawks", 193],
    ["Marshall Thundering Herd", 276],
    ["Texas State Bobcats", 326],
    ["Illinois Fighting Illini", 356],
    ["Duke Blue Devils", 150],
    ["Troy Trojans", 2653],
    ["Old Dominion Monarchs", 295],
    ["Vanderbilt Commodores", 238],
    ["Oklahoma State Cowboys", 197],
    ["Nevada Wolf Pack", 2440],
    ["Massachusetts Minutemen", 113],
    ["South Florida Bulls", 58],
    ["New Mexico State Aggies", 166],
    ["Kentucky Wildcats", 96],
    ["Michigan State Spartans", 127],
    ["Charlotte 49ers", 2429],
    ["San José State Spartans", 23],
    ["Nebraska Cornhuskers", 158],
    ["Western Michigan Broncos", 2711],
    ["Georgia State Panthers", 2247],
    ["Buffalo Bulls", 2084],
    ["New Mexico Lobos", 167],
    ["South Carolina Gamecocks", 2579],
    ["Wyoming Cowboys", 2751],
    ["Louisiana Tech Bulldogs", 2348],
    ["Eastern Michigan Eagles", 2199],
    ["Texas Longhorns", 251],
    ["Southern Miss Golden Eagles", 2572],
    ["Air Force Falcons", 2005],
    ["Alabama Crimson Tide", 333],
    ["Mississippi State Bulldogs", 344],
    ["Ole Miss Rebels", 145],
    ["Washington State Cougars", 265]
])
module.exports = fbsTeams;